import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { DynamicBackground } from "@/components/background";
import { QueryProvider } from "@/providers/QueryProvider";

import "../globals.css";

import { IntlayerProvider, getLocale } from "next-intlayer/server";
export { generateStaticParams } from "next-intlayer";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
    const locale = await getLocale();
    return (
        <html
			lang={locale}
			className={`${inter.variable} h-full antialiased`}
			data-glassmorphism="dark"
		>
            <body className="min-h-full flex flex-col">
				<DynamicBackground />
				<div id="app-root" className="flex min-h-full flex-1 flex-col">
					<IntlayerProvider locale={locale}>
						<QueryProvider>{children}</QueryProvider>
					</IntlayerProvider>
				</div>
			</body>
        </html>
    );
}
